name: Daily Auto Shorts

on:
  schedule:
    - cron: '0 9 * * *'  # كل يوم الساعة 9 صباحًا (UTC)
  workflow_dispatch:      # لتشغيله يدويًا من GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # أو يمكنك استخدام '3.x' للإصدار الأحدث

      - name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install moviepy
    pip install requests
    pip install google-api-python-client
    pip install oauth2client


